---
title: 'Exercise #3'
author: "Frederik Borutta (10345490) / Felix Borutta (10049639)"
date: "`r Sys.Date()`"
output: distill::distill_article
bibliography: packages.bib
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 1: Initializing git (4 Points)

a) Start by initializing a new R project with git support, called 2025-exeRcise-sheet-3. If you forgot
how to do this, you can follow this guide.


b) Commit the files generated by Rstudio.


c) For all of the following tasks in this exercise sheet we ask you to always commit your changes after
finishing each subtask e.g. create a commit after task 1d, 1e etc.
Note: This applies only to answers that have text or code as their answer. If you complete tasks
in a different order or forget to commit one, this is no problem. If you change your answers you
can just create multiple commits to track the changes.


d) Name 2 strengths and 2 weaknesses of git. (Don’t forget to create a commit after this answer, see 1c)

Strenghts:
  * Good for collaboration in teams, with multiple developers/contributers.
  * Branching and multiple merging strategies are possible.

Weaknesses:
  * Could be complex in the beginning, for example solving merge conflicts or to get a linear log graph with rebase strategy.
  * Git is mainly used for source code version control. Large files, containing multimedia content or similiar big data structures, are not supported well by git.

e) Knit this exercise sheet. Some new files will automatically be generated when knitting the sheet e.g. the
HTML page. Ignore these files, as we only want to track the source files themselves. You can, but
don’t need to create a .gitignore file. Just do not commit these files manually.


## Exercise 2: Putting your Repository on GitHub (3 Points)


## Exercise 3: Pixar Films (4 Points)


## Exercise 4: Open Analysis (4 points)
